CREATE TABLE "categories" (
  "id" SERIAL NOT NULL,
  "category" varchar(255) NOT NULL,
  PRIMARY KEY ("id")
);

INSERT INTO "categories" ("category") VALUES
('Motivation'),
('Historical'),
('Humor'),
('Life'),
('Philosophy'),
('Friendships'),
('Reading'),
('Nature'),
('Music'),
('Coding');

CREATE TABLE "authors" (
  "id" SERIAL NOT NULL,
  "author" varchar(255) NOT NULL,
  PRIMARY KEY ("id")
);

INSERT INTO "authors" ("author") VALUES
('William Shakespeare'),
('Stephen King'),
('Ernest Hemingway'),
('Oscar Wilde'),
('Albert Einstein'),
('Dr. Seuss'),
('Mark Twain'),
('Edgar Allan Poe'),
('Franklin D. Roosevelt'),
('John F. Kennedy'),
('Carl Sagan'),
('Martin Luther King Jr.'),
('Abraham Lincoln'),
('Winston Churchill'),
('Kurt Vonnegut'),
('Benjamin Franklin'),
('Warren Buffett'),
('Bill Gates'),
('Steve Jobs'),
('Linus Torvalds');

CREATE TABLE "quotes" (
  "id" SERIAL NOT NULL,
  "quote" text NOT NULL,
  "author_id" NOT NULL,
  "category_id" NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY (author_id) REFERENCES authors(id),
  FOREIGN KEY (category_id) REFERENCES categories(id)
);

INSERT INTO "quotes" ("quote", "author_id", "category_id") VALUES
('Heat not a furnace for your foe so hot that it do singe yourself.', 1, 4),
('Love all, trust a few, do wrong to none.', 1, 6),
('Some are born great, some achieve greatness, and some have greatness thrust upon them.', 1, 1),
('No legacy is so rich as honesty.', 1, 4),
('One touch of nature makes the whole world kin.', 1, 4),
('We love life, not because we are used to living, but because we are used to loving.', 1, 4),
('Boldness be my friend.', 1, 6),
('The robbed that smiles, steals something from the thief.', 1, 4),
('Such as we are made of, such we be.', 1, 4),
('Listen to many, speak to a few.', 1, 6),
('Brevity is the soul of wit.', 1, 4),
('Though she be but little, she is fierce.', 1, 1),
('In time we hate that which we often fear.', 1, 4),
('Love is too young to know what conscience is.', 1, 4),
('When words are scarce they are seldom spent in vain.', 1, 4),
('Monsters are real, and ghosts are real too. They live inside us, and sometimes, they win.', 2, 4),
('Fiction is the truth inside the lie.', 2, 4),
('Life is like a wheel. Sooner or later, it always comes around to where you started again.', 2, 4),
('When asked, How do you write? I invariably answer, one word at a time.', 2, 1),
('I can remember being home from school with tonsilitis and writing stories in bed to pass the time.', 2, 7),
('If you dont have the time to read, you dont have the time or the tools to write.', 2, 7),
('You cannot hope to sweep someone else away by the force of your writing until it has been done to you.', 2, 7),
('Every book you pick up has its own lesson or lessons, and quite often the bad books have more to teach than the good ones.', 2, 7),
('I had a period where I though I might not be good enough to publish.', 2, 1),
('You cant deny laughter. When it comes, it plops down in your favorite chair and stays as long as it wants.', 2, 4),
('I watched Titanic when I got back home from the hospital, and I cried. I knew that my IQ had been damaged.', 2, 3),
('We make up horrors to help us cope with the real ones.', 2, 4),
('Only enemies speak the truth. Friends and lovers lie constantly, caught in the web of duty.', 2, 6),
('Get busy living, or get busy dying.', 2, 4),
('Talent is cheaper than table salt. What separates the talented individual from the successful one is a lot of hard work.', 2, 1),
('Courage is grace under pressure.', 3, 4),
('The best way to find out if you can trust somebody is to trust them.', 3, 6),
('Never mistake motion for action.', 3, 4),
('Youre beautiful, like a may fly.', 3, 3),
('All things truly wicked start from innocence.', 3, 4),
('Hesitation increases in relation to risk in equal proportion to age.', 3, 4),
('Fear of death increases in exact proportion to increase in wealth.', 3, 4),
('Never think that war, no matter how neccessary, nor how justified, is not a crime.', 3, 2),
('Never go on trips with anyone you do not love.', 3, 6),
('Its none of their business that you have to learn how to write. Let them think you were born that way.', 3, 3),
('As you get older, it is harder to have heroes, but it is sort of neccessary.', 3, 4),
('There is only one thing in life worse than being talked about, and that is not being talked about.', 4, 4),
('Experience is simply the name we give our mistakes.', 4, 1),
('Who, being loved, is poor?', 4, 6),
('There are only two tragedies in life: one is not getting what one wants, and the other is getting it.', 4, 4),
('Life is never fair, and perhaps it is a good thing for most of us that it is not.', 4, 4),
('Success is a science. If you have the conditions, you get the result.', 4, 1),
('Bigamy is having one wife too many. Monogamy is the same.', 4, 3),
('Always forgive your enemies. Nothing annoys them so much.', 4, 3),
('The only thing to do with good advice is to pass it on. It is never of any use to oneself.', 4, 4),
('A man who does not think for himself does not think at all.', 4, 4),
('The truth is rarely pure and never simple.', 4, 4),
('No man is rich enough to buy back his past.', 4, 4),
('I can resist everything except temptation.', 4, 3),
('The world is a stage, but the play is badly cast.', 4, 3),
('I have simple tastes. I am always satisfied with the best.', 4, 3),
('We are all in the gutter, but some of us are looking at the stars.', 4, 4),
('Look deep into nature, and then you will understand everything better.', 5, 4),
('Reality is merely an illusion, albeit a very persistent one.', 5, 4),
('Only you can control your future.', 6, 1),
('The secret to getting ahead is getting started.', 7, 1),
('I would define, in breief, the poetry of words as the rhythmical creation of Beauty.', 8, 7),
('The only thing we have to fear is fear itself.', 9, 2),
('Victory has a thousand fathers, but defeat is an orphan.', 10, 2),
('Science is a way of thinking much more than it is a body of knowledge.', 11, 4),
('If a man has not discovered something that he will die for, he isnt fit to live.', 6, 2),
('You can fool all the people some of the time, and some of the people all the time, but you cannot fool all the people all the time.', 13, 4),
('The best argument against democracy is a five-minute conversation with the average voter.', 1, 3),
('You can always count on Americans to do the right thing - after theyve tried everything else.', 1, 3),
('Science is magic that works.', 15, 4),
('An investment in knowledge pays the best interest.', 16, 1),
('Someone is sitting in the shade today because someone planted a tree a long time ago.', 17, 1),
('Your most unhappy customers are your greatest source of learning.', 18, 1),
('Great things in business are never done by one person. Theyre done by a team of people.', 19, 1),
('You may lose a few hours of your productive daytime if you sleep, oh, say, ten hours a day, but those few hours when you are awake youre alert, and your brain functions on all six cylinders. Or four, or whatever.', 20, 4),
('The memory management on the PowerPC can be used to frighten small children.', 20, 10);